# Generated by Django 5.1.1 on 2025-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intro',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
