checkbox_statements = {
        'sensory_processing': "Sensory processing is the normal neurological process of organising sensations for our everyday life. Our brains receive sensory information from our bodies and surroundings, interpret these messages, and organise our purposeful responses.",
        'sensory_reactivity': "Sensory reactivity refers to the brain's regulation of its own activity. It is the process whereby information received through the senses is interpreted and organised to produce a response or behaviour that is appropriate to the sensory input. It plays an important role in a child’s level of arousal, ability to concentrate and attend to tasks, as well as to adapt to changes in the environment.",
        'sensory_discrimination': "Sensory Discrimination is the ability to differentiate sensory stimuli in order to make purposeful and adaptive responses.",
        'level_of_arousal': "Level of arousal, State of alertness. Naturally, our arousal level fluctuates throughout the day. However, in order to be functional and engage in tasks, we need to be “in sync” and be at an optimal level of arousal.",
        'window_of_tolerance': "Window of Tolerance describes the range in which a person can function and respond to stressors in a balanced way. In children with sensory reactivity issues, it explains their ability to process and react to sensory stimuli—such as sights, sounds, textures, and movements—without becoming overwhelmed or under-stimulated.  Understanding the child's window of tolerance helps caregivers and therapists to tailor interventions, creating environments that either minimize overwhelming stimuli or provide enough stimulation to keep the child engaged. The goal is to help children expand their window of tolerance, improving their sensory regulation and ability to manage everyday activities.",
        'taste_and_smell': "Taste and smell, Children with sensory integration needs often experience atypical taste and smell perception. Some may be overly sensitive, reacting strongly to certain smells or tastes, which can lead to aversions or picky eating. Others may have diminished perception, causing them to seek out strong flavors or smells to stimulate their senses. These differences in sensory processing can affect their food preferences, eating habits, and daily routines, potentially leading to challenges with nutrition, hygiene, and social interactions involving food or scents.",
        'tactile_perception': "Tactile perception refers to the ability to recognize and process information through touch, including texture, pressure, temperature, and vibration. In children with sensory integration difficulties, tactile perception can be significantly affected, leading to challenges in how they respond to everyday touch sensations.",
        'vestibular_sense': "Vestibular sense provides information through the inner ear about gravity and space, balance, and movement and about how our head and body position is in relation to the surface of the earth.",
        'proprioceptive_sense': "Proprioceptive sense provides information through our muscles and joints as to where our body parts are, how they are stretching and what they are doing.",
        'visual_perception': "Visual perception is the ability to give value and meaning to what is seen.",
        # 'postural_control': "Postural control involves maintaining the body in a state of stability in order for adequate participation in tasks. It includes postural tone, balance reactions, and maturation of the nervous system.",
        # 'postural_tone': "Postural tone is not the same as muscle strength and refers to the elasticity of the muscle fibres and the ability to allow us to maintain our bodies in specific positions against gravity. Good postural control is essential for the development of motor skills, coordination, and functional independence in activities like sitting, walking, playing sports, and performing daily tasks. Deficits in postural control can lead to difficulties with movement, coordination, and balance, impacting overall physical functioning.",
        'static_postural_control': "Static Postural Control, This is the ability to maintain balance and stability when stationary, such as standing or sitting without swaying or losing balance.",
        'dynamic_postural_control': "Dynamic Postural Control, This refers to maintaining stability during movement, such as walking, running, or bending to pick something up, where the body must constantly adjust to changes in motion.",
        'bilateral_integration': """Bilateral integration is the skill which enables a child to use the two sides of their body in a well-sequenced and coordinated way and gives one an idea as to how well the two sides of the brain are working together. This skill develops through several stages:
                    Symmetrical Movements (Infancy): Early bilateral integration involves both sides of the body moving in the same way simultaneously, such as reaching out with both hands or kicking with both legs. This stage is crucial for developing basic motor control.
                    Reciprocal Movements (Toddler Years): Children begin to use alternating movements, like crawling, walking, or climbing stairs. These movements involve both sides of the body working in a rhythm, laying the foundation for more complex motor activities.
                    Asymmetrical Movements (Preschool Years): As children gain motor control, they start performing tasks where one side of the body does something different from the other, such as using one hand to hold a paper while the other cuts with scissors. This stage enhances dexterity and functional independence.
                    Crossing the Midline (Early Childhood): The ability to reach across the body with one hand or leg to the opposite side, such as in activities like writing or catching a ball, is an important marker of bilateral integration. This indicates that both brain hemispheres are working together.
                    Complex Coordination (School Age): By this stage, children can engage in activities requiring precise and coordinated use of both sides of the body, like playing musical instruments, sports, or doing tasks requiring fine motor skills. This stage represents mature bilateral integration.
            """,
        'symmetric_movements': "Symmetrical Movements (Infancy): Early bilateral integration involves both sides of the body moving in the same way simultaneously, such as reaching out with both hands or kicking with both legs. This stage is crucial for developing basic motor control.",
        # 'reciprocal_movements': "Reciprocal Movements (Toddler Years): Children begin to use alternating movements, like crawling, walking, or climbing stairs. These movements involve both sides of the body working in a rhythm, laying the foundation for more complex motor activities.",
        # 'asymmetrical_movements': "Asymmetrical Movements (Preschool Years): As children gain motor control, they start performing tasks where one side of the body does something different from the other, such as using one hand to hold a paper while the other cuts with scissors. This stage enhances dexterity and functional independence.",
        # 'crossing_the_midline': "Crossing the Midline (Early Childhood): The ability to reach across the body with one hand or leg to the opposite side, such as in activities like writing or catching a ball, is an important marker of bilateral integration. This indicates that both brain hemispheres are working together.",
        # 'complex_coordination': "Complex Coordination (School Age): By this stage, children can engage in activities requiring precise and coordinated use of both sides of the body, like playing musical instruments, sports, or doing tasks requiring fine motor skills. This stage represents mature bilateral integration.",
        'praxis_or_motor_planing': """Praxis or motor planning is the ability to generate an idea of an action to be performed in a given situation. This idea is then organised into a plan which is then executed. This is dependent on well-developed body awareness. Together, these stages ensure smooth, coordinated movement and allow for learning from past actions to improve future motor planning. Deficits in motor planning can lead to challenges in performing everyday tasks, as seen in conditions like dyspraxia.  The stages of motor planning include:
                Ideation: This is the first stage where the individual forms the idea of the movement or task they want to perform. It involves recognizing the goal or purpose of the movement, such as deciding to pick up a cup or climb stairs.
                Planning: In this stage, the individual figures out how to accomplish the task. This involves selecting the appropriate motor actions, sequencing them, and considering the timing and coordination needed. For example, to pick up a cup, one needs to plan to reach out, grasp it, and lift it to the mouth.
                Execution: The individual carries out the planned movement. This stage involves activating the appropriate muscles and coordinating the necessary movements. The success of execution depends on how well the plan was formed and the ability to make adjustments as needed during the action.
                Feedback and Adaptation: After or during the movement, sensory feedback (from vision, touch, and proprioception) helps assess whether the movement was successful. If adjustments are needed, the individual makes corrections in real-time (during execution) or learns from the outcome to improve future motor plans.  
            """,
        'ideation': "Ideation: This is the first stage where the individual forms the idea of the movement or task they want to perform. It involves recognizing the goal or purpose of the movement, such as deciding to pick up a cup or climb stairs.",
        'planing': "Planing: In this stage, the individual figures out how to accomplish the task. This involves selecting the appropriate motor actions, sequencing them, and considering the timing and coordination needed. For example, to pick up a cup, one needs to plan to reach out, grasp it, and lift it to the mouth.",
        'execution': "Execution: The individual carries out the planned movement. This stage involves activating the appropriate muscles and coordinating the necessary movements. The success of execution depends on how well the plan was formed and the ability to make adjustments as needed during the action.",
        'feedback_and_adaptation': "Feedback and Adaptation: After or during the movement, sensory feedback (from vision, touch, and proprioception) helps assess whether the movement was successful. If adjustments are needed, the individual makes corrections in real-time (during execution) or learns from the outcome to improve future motor plans.",
        'sensory_integration': "Sensory integration",
        'tactile_reactivity': "Tactile Reactivity",
        'tactile_sensitivity': "Tactile Sensitivity (Hyperreactivity)",
        'tactile_under_responsiveness': "Tactile Under-Responsiveness (Hyporeactivity)",
        'tactile_defensiveness': "Tactile Defensiveness",
        'proprioceptive_processing': "Proprioceptive Processing",
        'body_awareness': "Body Awareness",
        'force_modulation': "Force Modulation",
        'movement_feedback': "Movement Feedback",
        'seeking_behaviors': "Seeking Behaviors",
        'vestibular_processing': "Vestibular Processing",
        'vestibular_sensitivity': "Vestibular Sensitivity (Hyperreactivity)",
        'vestibular_under_responsiveness': "Vestibular Under-Responsiveness (Hyporeactivity)",
        'movement_seeking': "Movement Seeking",
        'auditory_processing': "Auditory Processing",
        'auditory_discrimination': "Auditory Discrimination",
        'auditory_sensitivity': "Auditory Sensitivity (Hyperreactivity)",
        'auditory_under_responsiveness': "Auditory Under-Responsiveness (Hyporeactivity)",
        'auditory_overload': "Auditory Overload",
        'visual_processing': "Visual Processing",
        'visual_sensitivity': "Visual Sensitivity (Hyperreactivity)",
        'visual_under_responsiveness': "Visual Under-Responsiveness (Hyporeactivity)",
        'visual_discrimination': "Visual Discrimination",
        'visual_memory': "Visual Memory",
        'visual_sequential_memory': "Visual Sequential Memory",
        'visual_spatial_relationships': "Visual Spatial Relationships",
        'visual_figure_ground_discrimination': "Visual Figure-Ground Discrimination",
        'visual_closure': " Visual Closure",
        'visual_form_constancy': "Visual Form Constancy",
        'visual_tracking': "Visual Tracking (Oculomotor Control)",
        'visual_convergence': "Visual Convergence/Divergence",
        'visual_motor_integration': "Visual Motor Integration",
        'peripheral_vision_awareness': "Peripheral Vision Awareness",
        'depth_perception': "Depth Perception",
        'visual_attention': "Visual Attention",
        'simultaneous_processing_of_visual_information': "Simultaneous Processing of Visual Information",
        'auditory_visual_integration': "Auditory-Visual Integration",
        'multisensory_integration': "Multisensory Integration",
        'olfactory_processing': "Olfactory (Smell) Processing",
        'olfactory_sensitivity': "Olfactory Sensitivity (Hyperreactivity)",
        'olfactory_under_responsiveness': "Olfactory Under-Responsiveness (Hyporeactivity)",
        'gustatory_processing': "Gustatory (Taste) Processing",
        'taste_sensitivity': "Taste Sensitivity (Hyperreactivity)",
        'taste_under_responsiveness': "Taste Under-Responsiveness (Hyporeactivity)",
        'interoception': "Interoception",
        'awareness_of_internal_body_states': "Awareness of Internal Body States",
        'interoceptive_regulation': "Interoceptive Regulation",
        # Physical Skills
        'reflex_integration': "Reflex Integration",
        'persistence_of_primitive_reflexes': "Persistence of Primitive Reflexes",
        'postural_reactions': "Postural Reactions",
        'motor_planing': "Motor Planing (Praxis)",
        'physical_skills_ideation': "Physical Skills Ideation",
        'physical_skills_sequencing': "Physical Skills Sequencing",
        'physical_skills_planing': "Physical Skills Planning",
        'physical_skills_execution': "Physical Skills Execution",
        'physical_skills_feedback_and_adaptation': "Physical Skills Feedback and Adaptation",
        # Grass Motor Skills
        'mobility': "Mobility",
        'gait': "Gait",
        'transitions': "Transitions",
        'jumping': "Jumping",
        'climbing': "Climbing",
        'postural_control': "Postural Control",
        'balance': "Balance",
        'postural_tone': "Postural tone",
        'static_balance': "Static Balance",
        'dynamic_balance': "Dynamic Balance",
        'core_strength': "Core Strength",
        'sitting_posture': "Sitting Posture",
        'standing_posture': "Standing Posture",
        'coordination': "Coordination",
        'bilateral_coordination': "Bilateral Coordination",
        'symmetrical_movements': "Symmetrical Movements (Infancy)",
        'reciprocal_movements': "Reciprocal Movements (Toddler Years)",
        'asymmetrical_movements': "Asymmetrical Movements (Preschool Years)",
        'crossing_the_midline': "Crossing the Midline (Early Childhood)",
        'complex_coordination': "Complex Coordination (School Age)",
        'hand_eye_coordination': "Hand-Eye Coordination",
        'foot_eye_coordination': "Foot-Eye Coordination",
        'body_strength_endurance': "Body Strength and Endurance",
        'muscle_strength': "Muscle Strength",
        'stamina': "Stamina",
    }